[package]
name = "simple-nn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = "0.20.0"
tch = "0.11.0" # load dataset
# tensorflow = { version = "0.20.0", features = ["tensorflow_gpu"] }